services:
    # imagem
    api:
        container_name: petshop-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./back:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - petshop-network

    # nginx
    nginx:
        container_name: petshop-nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
        - '8010:80'
        volumes:
        - ./back:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - petshop-network

    # mysql
    db_petshop:
        container_name: petshop-mysql
        image: mysql:8.0
        restart: unless-stopped
        ports:
          - 3307:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./back/.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - petshop-network

networks:
    petshop-network:
        driver: bridge  
          
